name: Run pytest on PR merge

on:
  pull_request:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest

    # Only run this job if the PR was merged into the main branch
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run pytest
        run: pytest tests
