name: tweet_periodically
on:
  schedule:
    # 日本時間でも UTC でも (3 の倍数) 時 00 分に実行
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy

      - name: Make Tweet
        run: |
          python tweet.py ${{secrets.CONSUMER_KEY}} ${{secrets.CONSUMER_SECRET}} ${{secrets.ACCESS_TOKEN}} ${{secrets.ACCESS_TOKEN_SECRET}}
        env:
          TZ: 'Asia/Tokyo'
